/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import static java.awt.Color.black;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import logic.Export;

/**
 *
 * @author MARQUEZ
 */
public class JFExport extends javax.swing.JFrame {

    private String text;
    private JFileChooser fileChooser;
    private Color selectedColor;
    
    /**
     * Creates new form JFPrint
     */
    public JFExport() {
        initComponents();
    }

    JFExport(String text) {
        this.selectedColor = Color.BLACK;
        this.text = text;
        initComponents();
        fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        setDefaultCloseOperation(JFExport.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bBack = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        lTitle = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lExtension = new javax.swing.JLabel();
        lPath = new javax.swing.JLabel();
        tFName = new javax.swing.JTextField();
        cBExtension = new javax.swing.JComboBox<>();
        tFPath = new javax.swing.JTextField();
        bChoosePath = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bBack.setText("Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        lTitle.setText("SAVE TRANSLATION");

        lName.setText("Name");

        lExtension.setText("Extension");

        lPath.setText("Path");

        cBExtension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TXT", "PNG" }));

        bChoosePath.setText("...");
        bChoosePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChoosePathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tFName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cBExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(tFPath, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bChoosePath, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lName)
                        .addGap(108, 108, 108)
                        .addComponent(lExtension)
                        .addGap(116, 116, 116)
                        .addComponent(lPath)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(bSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bBack)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(lTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(lExtension)
                    .addComponent(lPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bChoosePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBack)
                    .addComponent(bSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bBackActionPerformed

    private void bChoosePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChoosePathActionPerformed
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFolder = fileChooser.getSelectedFile();
            tFPath.setText(selectedFolder.getAbsolutePath());
        }
    }//GEN-LAST:event_bChoosePathActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        String format = (String) cBExtension.getSelectedItem();
        String filename = tFName.getText();
        String filePath = tFPath.getText();

        if (filePath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una carpeta para guardar el archivo.");
            return;
        }

        if (!filename.toLowerCase().endsWith("." + format.toLowerCase())) {
            filename += "." + format.toLowerCase();
        }

        File file = new File(filePath, filename);
        if (!file.getParentFile().isDirectory()) {
            JOptionPane.showMessageDialog(this, "La ruta seleccionada no es un directorio válido.");
            return;
        }

        try {
            Export exportService = new Export();
            exportService.exportBraille(file, format, text, 14, false, false, black);
            JOptionPane.showMessageDialog(this, "Texto guardado correctamente como " + format);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage());
        }
    }//GEN-LAST:event_bSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bChoosePath;
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox<String> cBExtension;
    private javax.swing.JLabel lExtension;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPath;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tFName;
    private javax.swing.JTextField tFPath;
    // End of variables declaration//GEN-END:variables
}
